[2023-04-09T23:30:54.857+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_all_pandas_vinicius.xlsx_to_csv scheduled__2023-04-08T23:30:43.442659+00:00 [queued]>
[2023-04-09T23:30:54.867+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_all_pandas_vinicius.xlsx_to_csv scheduled__2023-04-08T23:30:43.442659+00:00 [queued]>
[2023-04-09T23:30:54.867+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-09T23:30:54.867+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 6
[2023-04-09T23:30:54.867+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-09T23:30:54.884+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): xlsx_to_csv> on 2023-04-08 23:30:43.442659+00:00
[2023-04-09T23:30:54.890+0000] {standard_task_runner.py:55} INFO - Started process 133 to run task
[2023-04-09T23:30:54.892+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'etl_all_pandas_vinicius', 'xlsx_to_csv', 'scheduled__2023-04-08T23:30:43.442659+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag_vinicius.py', '--cfg-path', '/tmp/tmp9i5lnboq']
[2023-04-09T23:30:54.892+0000] {standard_task_runner.py:83} INFO - Job 12: Subtask xlsx_to_csv
[2023-04-09T23:30:54.943+0000] {task_command.py:389} INFO - Running <TaskInstance: etl_all_pandas_vinicius.xlsx_to_csv scheduled__2023-04-08T23:30:43.442659+00:00 [running]> on host c8c0de2c14c7
[2023-04-09T23:30:55.007+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_all_pandas_vinicius
AIRFLOW_CTX_TASK_ID=xlsx_to_csv
AIRFLOW_CTX_EXECUTION_DATE=2023-04-08T23:30:43.442659+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-08T23:30:43.442659+00:00
[2023-04-09T23:30:55.009+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-09T23:30:55.009+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'soffice --headless --nologo --norestore --convert-to ods --outdir /tmp/ /tmp/vendas.xls']
[2023-04-09T23:30:55.021+0000] {subprocess.py:86} INFO - Output:
[2023-04-09T23:30:55.861+0000] {subprocess.py:93} INFO - 
[2023-04-09T23:30:55.862+0000] {subprocess.py:93} INFO - (process:201): dconf-CRITICAL **: 23:30:55.861: unable to create directory '/home/***/.cache/dconf': Permission denied.  dconf will not work properly.
[2023-04-09T23:31:01.281+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-04-09T23:31:01.301+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-04-09T23:31:01.308+0000] {taskinstance.py:1332} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_all_pandas_vinicius, task_id=xlsx_to_csv, execution_date=20230408T233043, start_date=20230409T233054, end_date=20230409T233101
[2023-04-09T23:31:01.333+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 12 for task xlsx_to_csv (Bash command failed. The command returned a non-zero exit code 1.; 133)
[2023-04-09T23:31:01.375+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-09T23:31:01.424+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
